# action.yml
name: 'Load used actions'
author: 'Rob Bos'
description: 'Load an overview of all used actions in a GitHub Organization (or user account)'
branding:
  icon : download
  color: orange
inputs:
  organization:
    description: 'Slug of the organization to analyze. Leave empty for current organization'
    required: false
  PAT:
    description: 'Personal access token to use for analysis. Leaving this empty will use the default GITHUB_TOKEN that could have limited access rights'
    required: true 
outputs:
  actions:
    description: 'List of all actions used in the organization'  
  actions-file:
    description: 'Location of the file containing the list of all actions used in the organization'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - '${{ inputs.organization }}' 
    - '${{ inputs.PAT }}' 