name: Lint GitHub Actions workflows
on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read
  pull-requests: write

jobs:
  actionlint:
    uses: devops-actions/.github/.github/workflows/actionlint.yml@b77cea6d7ba1cd4e001581783cc592bbb63ce46d # main
    permissions:
      contents: read
      pull-requests: write