name: Validate Action Examples

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  validate-examples:
    uses: devops-actions/.github/.github/workflows/actions-example-checker.yml@d364c735203f99cf570835e235fc73e82cd170a5 # main
    permissions:
      contents: read