name: Validate Action Examples

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  validate-examples:
    uses: devops-actions/.github/.github/workflows/actions-example-checker.yml@672aa7567d97943087954938e9fdce6658f36917 # main
    permissions:
      contents: read