name: "Approve Dependabot PR's" 
on:
  pull_request:

permissions:
  contents: read

jobs:
  dependabot:
    permissions:
      contents: write
      pull-requests: write
      actions: write
    uses: devops-actions/.github/.github/workflows/approve-dependabot-pr.yml@891fb6d59e53d81ffc7e9367de68d4ef288f2900 # main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
