name: "Approve Dependabot PR's" 
on:
  pull_request:

permissions:
  contents: read

jobs:
  dependabot:
    permissions:
      contents: write
      pull-requests: write
      actions: write
    uses: devops-actions/.github/.github/workflows/approve-dependabot-pr.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
